version: '3'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16

services:
  simon:
    build: ./reseau_interne/simon
    networks:
      default:
        ipv4_address: 192.168.0.200
    container_name: simon
    hostname: simon
    dns: 192.168.0.7

  pauline:
    build: ./reseau_interne/pauline
    networks:
      default:
        ipv4_address: 192.168.0.201
    container_name: pauline
    hostname: pauline
    dns: 192.168.0.7
    
  saskia:
    build: ./reseau_interne/saskia
    networks:
      default:
        ipv4_address: 192.168.0.202
    container_name: saskia
    hostname: saskia
    dns: 192.168.0.7

  resolver:
    build: ./reseau_interne/resolver
    networks:
      default:
        ipv4_address: 192.168.0.7
    container_name: resolver
    hostname: resolver

  soa:
    build: ./reseau_interne/soa
    networks:
      default:
        ipv4_address: 192.168.0.4
    container_name: soa
    hostname: soa 

  web:
    build: ./reseau_interne/web
    networks:
      default:
        ipv4_address: 192.168.0.2
    container_name: web
    hostname: web
    dns: 192.168.0.4
    depends_on: 
      - db



  db:
    build: ./reseau_interne/DB
    networks:
      default:
        ipv4_address: 192.168.0.3
    container_name: db
    hostname: db 
    dns: 192.168.0.4
