version: '3'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16

services:
  simon:
    build: ./reseau_interne/simon
    networks:
      default:
        ipv4_address: 192.168.0.200
    container_name: simon
    hostname: simon
    dns: 192.168.0.7

  pauline:
    build: ./reseau_interne/pauline
    networks:
      default:
        ipv4_address: 192.168.0.201
    container_name: pauline
    hostname: pauline
    dns: 192.168.0.7
    
  saskia:
    build: ./reseau_interne/saskia
    networks:
      default:
        ipv4_address: 192.168.0.202
    container_name: saskia
    hostname: saskia
    dns: 192.168.0.7

  resolver:
    build: ./reseau_interne/resolver
    networks:
      default:
        ipv4_address: 192.168.0.7
    container_name: resolver
    hostname: resolver

  web:
    build: ./reseau_interne/web
    networks:
      default:
        ipv4_address: 192.168.0.2
    container_name: web
    hostname: web
    dns: 192.168.0.4
    depends_on: 
      - db

  db:
    build: ./reseau_interne/DB
    networks:
      default:
        ipv4_address: 192.168.0.3
    container_name: db
    hostname: db 
    expose:
      - 3306
    ports:
      - "3306:3306"
    dns: 192.168.0.4

  soa:
    build: ./reseau_interne/soa
    networks:
      default:
        ipv4_address: 192.168.0.4
    container_name: soa
    hostname: soa

  mail:
    build: ./reseau_interne/mail
    networks:
      default:
        ipv4_address: 192.168.0.5
    container_name: mail
    hostname: mail 
    dns: 192.168.0.4
    environment: 
      - maildomain=woodytoys.lab

  ns_public:
    build: ./reseau_externe/ns
    networks:
      default:
        ipv4_address: 192.168.0.9
    ports:
      - "209.38.227.83:53:53/tcp"
      - "209.38.227.83:53:53/udp"
    container_name: ns_public

  web_public:
    build: ./reseau_externe/web
    networks:
      default:
        ipv4_address: 192.168.0.10
    ports:
      - "80:80"
      - "443:443"
    container_name: web_public
    depends_on:
      - db

  mail_public:
    build: ./reseau_externe/mail
    networks:
      default:
        ipv4_address: 192.168.0.11
    container_name: mail_public
    hostname: mail 
    dns: 192.168.0.4
    tty: true
    environment:
      - maildomain=mmes-2.ephec-ti.be
    ports:
      - "2525:25"
      - "110:110"
      - "143:143"
      - "587:587"
      - "993:993"

  simon_public:
    build: ./reseau_externe/simon
    networks:
      default:
        ipv4_address: 192.168.0.12
    container_name: simon_public
    hostname: simon_public
    dns: 192.168.0.4
    tty: true
