version: "3.8"

services:
  resolver:
    container_name: 'resolver'
    build: ./reseau_interne/resolver
    expose:
      - 53/udp
      - 53/tcp
    networks:
      secure_zone:
        ipv4_address: 192.168.0.1
  web:
    container_name: 'web'
    build: ./reseau_interne/web
    links:
      - db:db
    expose:
      - 80
      - 443
    networks:
      secure_zone:
        ipv4_address: 192.168.0.2
  db:
    container_name: 'db'
    build: ./reseau_interne/db
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3307
    ports:
      - 3307:3307
    networks:
      secure_zone:
        ipv4_address: 192.168.0.3
  mail:
    container_name: 'mail'
    build: ./reseau_interne/mail
    expose:
      - 25
      - 143
      - 587
      - 993
    networks:
      secure_zone:
        ipv4_address: 192.168.0.4
  client_simon:
    image: alpine
    command: ash -c "apk update && apk upgrade && apk add links lynx bind-tools busybox-extras mysql && echo -e 'search ephec.be\nnameserver 192.168.0.1\noptions edns0 trust-ad ndots:0' > /etc/resolv.conf && tail -f /dev/null"
    container_name: simon
    networks:
      secure_zone:
        ipv4_address: 192.168.0.200
  client_pauline:
    image: alpine
    command: ash -c "apk update && apk upgrade && apk add links lynx bind-tools busybox-extras mysql && echo -e 'search ephec.be\nnameserver 192.168.0.1\noptions edns0 trust-ad ndots:0' > /etc/resolv.conf && tail -f /dev/null"
    container_name: pauline
    networks:
      secure_zone:
        ipv4_address: 192.168.0.201
  client_saskia:
    image: alpine
    command: ash -c "apk update && apk upgrade && apk add links lynx bind-tools busybox-extras mysql && echo -e 'search ephec.be\nnameserver 192.168.0.1\noptions edns0 trust-ad ndots:0' > /etc/resolv.conf && tail -f /dev/null"
    container_name: saskia
    networks:
      secure_zone:
        ipv4_address: 192.168.0.202
volumes:
  db-data:
networks:
  secure_zone:
    ipam:
      driver: default
      config: 
        - subnet: 192.168.0.0/16
          gateway: 192.168.254.254